version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hakimfrh/whatsapp-api:latest
    volumes:
      - data:/app/data
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"  # Map port 3000 inside the container to port 3000 on your host machine

volumes:
  data:
