version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hakimfrh/whatsapp-api:latest
    volumes:
      - data:/app/data
    environment:
      - NODE_ENV=production
    annotations:
      dev.okteto.com/auto-ingress: "true"
      # Add additional environment variables if needed

volumes:
  data:
